version = 0.1
[default.deploy.parameters]
stack_name = "samp-aoo-test"
resolve_s3 = true
s3_prefix = "samp-aoo-test"
region = "us-east-1"
profile = "Personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
