on:
  push:
    branches:
      - main
    paths:
      - 'src/SAM/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ADMIN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          cd src/SAM
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset