name: Verify Changes - Publish Plan to PR

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    types: [opened]
    paths:
      - 'src/SAM/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
          pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ADMIN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          ls -d */
          cd src/
          ls -d */
          cd SAM/
          sam deploy --no-execute-changeset --stack-name sam-backend

      - name: Post plan to PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Hello**
            🌏
            !