name: Verify build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  push:
    branches:
      - master
    paths:
      - 'src/staticSite/SAM/**'

jobs:
  lint:
    runs-on: windows-latest
    strategy:
        matrix:
            python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pip install pylint
      - run: pip install -r ".\src\SAM\Lambda\requirements.txt"
      - run: pip install moto
      - run: |
          $results = pylint ".\src\SAM\Lambda\app.py" --disable=C0114,C0115,C0116,E0110,E1101,E1123,R0801,C0103,W0613,W0612
          write-output($results)
          $pattern = "(?<=rated at )(\d+\.\d+)(?=/10)"
          $match = [regex]::Match($results, $pattern)
          $score = $match.Groups[1].Value
          $score = [int]$score
          write-output($score)
          if ($score -gt '6'){
            echo("looks good")
            exit 0
          }else{
            echo("fix your code")
            exit 1
          }
        shell: pwsh

  unit_test: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          Copy-Item "${GITHUB_WORKSPACE}\tests\unit\test_app.py" -Destination "${GITHUB_WORKSPACE}\src\SAM\Lambda\test_app.py"
          pytest -v .\src\SAM\Lambda\test_app.py
        shell: pwsh

    
